const projects = [
  {
    id: 1,
    title: "This Webpage!!",
    description: "Webpage dedicated to showcasing my projects and experience over the years. Currently at Version 3.2 with a new design and improved functionality.",
    details: "This portfolio website was rebuilt to highlight projects, experience, and technical skills. The card layout, filter chips, pagination, and modal gallery were designed for responsive browsing on both desktop and mobile devices.",
    collaborators: [],
    images: [
      "assets/img/ProjectsImages/MyCV/MyCVPage.png"    ],
    language: ["JavaScript", "HTML"],
    technology: ["GitHub"],
    domain: ["Web Application"],
    image: "assets/img/ProjectsImages/MyCV/MyCVPage.png",
    logo: "assets/img/icon/MRKCSCircularLogoWhite.png",
    logoAlt: "MyCV project logo",
    startMonth: "May 2026",
    endMonth: "Jun 2026",
  },
  {
    id: 2,
    title: "Accede 2026",
    description: "Hired again by 5 different schools to maintain their booking systems, update their stock, and handle administrative tasks.",
    details: "The Accede 2026 project involved updating bookings, managing inventory, and streamlining administrative workflows for multiple schools. I worked closely with school staff to ensure the system remained stable during peak enrollment seasons.",
    collaborators: ["Charo Blanco", "Natalia Gómez", "School Coordinators"],
    images: [
      "assets/img/ProjectsImages/Accede2026/image.png"    ],
    language: [],
    technology: ["Accede"],
    domain: ["Education"],
    image: "assets/img/ProjectsImages/Accede2026/image.png",
    logo: "assets/img/icon/LibreriaKaori.jpg",
    logoAlt: "Accede 2026 logo",
    startMonth: "Jun 2026",
    endMonth: "Sep 2026",
  },
  {
    id: 3,
    title: "Accede 2025",
    description: "Hired by 5 different schools to maintain their booking systems, update their stock, and handle administrative tasks.",
    details: "This earlier Accede engagement focused on system maintenance, school booking accuracy, and stock reconciliation. I implemented improvements that reduced manual corrections and improved reporting transparency.",
    collaborators: ["Charo Blanco", "Vanesa Martin", "School Coordinators"],
    images: [
      "assets/img/ProjectsImages/Accede2025/image.png",
      null,
      null,
    ],
    language: [],
    technology: ["Accede"],
    domain: ["Education"],
    image: "assets/img/ProjectsImages/Accede2025/image.png",
    logo: "assets/img/icon/LibreriaKaori.jpg",
    logoAlt: "Accede 2025 logo",
    startMonth: "Jun 2025",
    endMonth: "Sep 2025",
  },
  {
    id: 4,
    title: "Quillyz Website",
    description: "A trip hosting and social media platform for connecting users with similar interests. Worked at the backend improving recommendation algorithms user satisfaction.",
    details: "For Quillyz I developed backend services to enhance recommendations and improve user discovery. The work included API integration, data modeling, and algorithm tuning for personalized trip suggestions.",
    collaborators: ["Steven Mallqui Aguilar"],
    images: [
      "assets/img/ProjectsImages/Quillyz/Image.png",
      "assets/img/ProjectsImages/Quillyz/Image2.png",
      "assets/img/ProjectsImages/Quillyz/Image3.png",
      "assets/img/ProjectsImages/Quillyz/Image4.png",
      "assets/img/ProjectsImages/Quillyz/Image5.png",
    ],
    language: ["JavaScript", "Python", "MongoDB"],
    technology: ["Node.js", "Docker", "GitHub", "Clustering Algorithms", "Genetic Algorithms"],
    domain: ["Web Application", "AI"],
    image: "assets/img/ProjectsImages/Quillyz/Image.png",
    logo: "assets/img/icon/UCMIcon.png",
    logoAlt: "Quillyz project logo",
    startMonth: "May 2024",
    endMonth: "Sep 2024",
  },
  {
    id: 5,
    title: "Kaori E-Commerce",
    description: "Electric Commerce for my bookshop, dedicated to showcase events, dropshipping and online sales.",
    details: "This project launched an online storefront for a bookstore, supporting event promotion, inventory management, and online orders. The site was built to balance e-commerce conversion with brand presence.",
    collaborators: ["Charo Blanco"],
    images: [
      null,
      null,
      null,
    ],
    language: [],
    technology: ["Odoo"],
    domain: ["E-commerce"],
    image: null,
    logo: "assets/img/icon/LibreriaKaori.jpg",
    logoAlt: "Kaori E-Commerce logo",
    startMonth: "Dec 2025",
    endMonth: "Dec 2025",
  },
  {
    id: 6,
    title: "Poker Equity Tool",
    description: "Calculated poker equity for different cards, showing you your odds adapting to on table cards.",
    details: "The Poker Equity Tool is a desktop solution that calculates hand odds and equity during gameplay. It was designed for quick evaluations and includes algorithms to compare hand combinations in real time.",
    collaborators: ["Mario Gonzalez", "Asier Rodriguez", "Jose Luis"],
    images: [
      null,
      null,
      null,
    ],
    language: ["Java"],
    technology: [],
    domain: ["Desktop Application"],
    image: null,
    logo: "assets/img/icon/UCMIcon.png",
    logoAlt: "Poker Equity Tool logo",
    startMonth: "Oct 2021",
    endMonth: "Dec 2021",
  },
  {
    id: 10,
    title: "Functional Evolution Optimizer",
    description: "A system for evolving functional programming paradigms based on Darwins theory of evolution. Uses genetic algorithms to optimize function parameters.",
    details: "This project combined evolutionary algorithms with practical optimization to evolve and refine software behavior. It includes a configurable fitness function and iterative evaluation for automated improvement.",
    collaborators: ["Zhenbo Chen"],
    images: [
      null,
      null,
      null,
    ],
    language: ["Java", "C++"],
    technology: ["Genetic Algorithms"],
    domain: ["AI", "Desktop Application"],
    image: null,
    logo: "assets/img/icon/UCMIcon.png",
    logoAlt: "Functional Evolution Optimizer logo",
    startMonth: "Mar 2022",
    endMonth: "May 2022",
  },
  {
    id: 11,
    title: "Remmi personal assistant",
    description: "Mobile assistant for managing conversation and calendar events and appointments.",
    details: "Remmi is a mobile assistant designed to manage conversations, schedules, and reminders using intelligent automation. It combines mobile UX design with backend automation to help users organize daily activities.",
    collaborators: [],
    images: [
      "assets/img/ProjectsImages/Remmi/Remmi2.png",
      null,
      null,
    ],
    language: ["C", "C++", "Python"],
    technology: ["Android", "Genetic Algorithms", "Clustering Algorithms"],
    domain: ["Mobile", "AI"],
    image: "assets/img/ProjectsImages/Remmi/Remmi3.png",
    logo: "assets/img/icon/MRKCSCircularLogoWhite.png",
    logoAlt: "Remmi personal assistant logo",
    startMonth: "May 2024",
    endMonth: "Jul 2024",
  }
];
